name: deploy-feature

on: 
  push:
    branches: "feature-*"
    
jobs:
  continuous-deployment-to-feature-branch: 
    runs-on: ubuntu-latest
    steps:
        # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: "Install Node"
          uses: "actions/setup-node@v2"
          with:
            cache: "yarn"
            node-version: "16"
          
        - name: "Install dependencies"
          run: "yarn install"

        - name: "Generate subgraph manifest"
          run: "yarn run prepare:goerli"
        
        - name: "Generate AssemblyScript types"
          run: "yarn run codegen"

        # For simplicity, we can say we only deploy feature branch to Kovan
        - name: "Deploy to Kovan"
          run: "yarn run deploy:feature --access-token ${{ secrets.GRAPH_ACCESS_TOKEN }}"

